language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean check
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube -Dsonar.organization=konstantin-krylov -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=da994964daf1d6f93cba8cd4fff7c0a539d2a9f7

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="822f69c1-ef26-441c-8f2c-5e08ead2524e"